parserOptions:
  ecmaVersion: 2018
env:
  es6: true
  node: true
extends: 'eslint:recommended'
rules:
  strict:
    - error
    - global
  indent:
    - error
    - 2
  linebreak-style:
    - error
    - unix
  quotes:
    - error
    - single
  semi:
    - error
    - always
